# Generated by Django 3.1.1 on 2023-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('brandname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=80)),
                ('manufacturedate', models.DateField()),
                ('expiredate', models.DateField()),
            ],
            options={
                'permissions': (('view_labs', 'Can view lab details.'), ('view_marks', 'can view semester marks')),
            },
        ),
    ]
