# Generated by Django 3.1.1 on 2023-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=80)),
                ('emailid', models.EmailField(max_length=254)),
            ],
            options={
                'permissions': (('view_labs', 'Can view lab details.'), ('view_marks', 'can view semester marks')),
            },
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
