# Generated by Django 3.1.1 on 2023-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230405_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
